image: golang:1.9

variables:
  REPO_NAME: gitlab.com/clover/SeFTP

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

stages:
  - build

build-project:
  stage: build
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - cd $GOPATH/src/$REPO_NAME/server
    - go build main.go
    - cd $GOPATH/src/$REPO_NAME/client
    - go build main.go
